# Performing EDA and predicting penguins species by using Logistic Regression.

* Multiclass Classification.

In [147]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import warnings # ignore warnings
warnings.filterwarnings("ignore")

In [188]:
df = pd.read_csv('penguins.csv')
df.tail()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,FEMALE
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,MALE
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,FEMALE
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,MALE


In [149]:
df.columns # it will give name of columns of dataset

Index(['species', 'island', 'bill_length_mm', 'bill_depth_mm',
       'flipper_length_mm', 'body_mass_g', 'sex'],
      dtype='str')

In [150]:
df.duplicated().sum() # data have no duplicate values in it.

np.int64(0)

In [151]:
df.drop(columns= ['island','sex'],inplace = True)
df.head()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
0,Adelie,39.1,18.7,181.0,3750.0
1,Adelie,39.5,17.4,186.0,3800.0
2,Adelie,40.3,18.0,195.0,3250.0
3,Adelie,NaN,NaN,NaN,NaN
4,Adelie,36.7,19.3,193.0,3450.0


* changing body mass into kilograms(kg).

In [195]:
df['body_mass_kg'] = df['body_mass_g']/1000
df.head()

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex,body_mass_kg
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE,3.75
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE,3.80
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE,3.25
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE,3.45


In [153]:
df.drop(columns= ['body_mass_g'],inplace =True)
df.head()

,species,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg
0,Adelie,39.1,18.7,181.0,3.75
1,Adelie,39.5,17.4,186.0,3.80
2,Adelie,40.3,18.0,195.0,3.25
3,Adelie,NaN,NaN,NaN,NaN
4,Adelie,36.7,19.3,193.0,3.45


In [154]:
df.describe()

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg
count,342.000000,342.000000,342.000000,342.000000
mean,43.921930,17.151170,200.915205,4.201754
std,5.459584,1.974793,14.061714,0.801955
min,32.100000,13.100000,172.000000,2.700000
25%,39.225000,15.600000,190.000000,3.550000
50%,44.450000,17.300000,197.000000,4.050000
75%,48.500000,18.700000,213.000000,4.750000
max,59.600000,21.500000,231.000000,6.300000


In [155]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    str    
 1   bill_length_mm     342 non-null    float64
 2   bill_depth_mm      342 non-null    float64
 3   flipper_length_mm  342 non-null    float64
 4   body_mass_kg       342 non-null    float64
dtypes: float64(4), str(1)
memory usage: 13.6 KB


In [156]:
df.isnull().sum()

species              0
bill_length_mm       2
bill_depth_mm        2
flipper_length_mm    2
body_mass_kg         2
dtype: int64

* filing null(int/float) values with their mean values 

In [157]:
df['bill_depth_mm'] = df['bill_depth_mm'].fillna(df['bill_depth_mm'].mean())
df['bill_depth_mm'].isnull().sum()

np.int64(0)

In [158]:
df['bill_length_mm'] = df['bill_length_mm'].fillna(df['bill_length_mm'].mean())
df['flipper_length_mm'] = df['flipper_length_mm'].fillna(df['flipper_length_mm'].mean())
df['body_mass_kg'] = df['body_mass_kg'].fillna(df['body_mass_kg'].mean())


In [159]:
df.isnull().sum()

species              0
bill_length_mm       0
bill_depth_mm        0
flipper_length_mm    0
body_mass_kg         0
dtype: int64

# now the data is cleaned

In [160]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 344 entries, 0 to 343
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   species            344 non-null    str    
 1   bill_length_mm     344 non-null    float64
 2   bill_depth_mm      344 non-null    float64
 3   flipper_length_mm  344 non-null    float64
 4   body_mass_kg       344 non-null    float64
dtypes: float64(4), str(1)
memory usage: 13.6 KB


In [161]:
df.columns

Index(['species', 'bill_length_mm', 'bill_depth_mm', 'flipper_length_mm',
       'body_mass_kg'],
      dtype='str')

In [162]:
x = df[['bill_length_mm', 'bill_depth_mm','flipper_length_mm','body_mass_kg']]
y = df['species']

In [163]:
x

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_kg
0,39.10000,18.70000,181.000000,3.750000
1,39.50000,17.40000,186.000000,3.800000
2,40.30000,18.00000,195.000000,3.250000
3,43.92193,17.15117,200.915205,4.201754
4,36.70000,19.30000,193.000000,3.450000
...,...,...,...,...
339,43.92193,17.15117,200.915205,4.201754
340,46.80000,14.30000,215.000000,4.850000
341,50.40000,15.70000,222.000000,5.750000
342,45.20000,14.80000,212.000000,5.200000


In [164]:
y

0      Adelie
1      Adelie
2      Adelie
3      Adelie
4      Adelie
        ...  
339    Gentoo
340    Gentoo
341    Gentoo
342    Gentoo
343    Gentoo
Name: species, Length: 344, dtype: str

* transforming y feature into 0,1,2 format

In [165]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [166]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,

In [167]:
from sklearn.model_selection import train_test_split

In [168]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.3,random_state=23)

In [169]:
from sklearn.linear_model import LogisticRegression

In [170]:
model = LogisticRegression()

In [171]:
model.fit(x_train,y_train)

,"penalty penalty: {'l1', 'l2', 'elasticnet', None}, default='l2'Specify the norm of the penalty:- `None`: no penalty is added;- `'l2'`: add a L2 penalty term and it is the default choice;- `'l1'`: add a L1 penalty term;- `'elasticnet'`: both L1 and L2 penalty terms are added... warning:: Some penalties may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionadded:: 0.19 l1 penalty with SAGA solver (allowing 'multinomial' + L1).. deprecated:: 1.8 `penalty` was deprecated in version 1.8 and will be removed in 1.10. Use `l1_ratio` instead. `l1_ratio=0` for `penalty='l2'`, `l1_ratio=1` for `penalty='l1'` and `l1_ratio` set to any float between 0 and 1 for `'penalty='elasticnet'`.",'deprecated'
,"C C: float, default=1.0Inverse of regularization strength; must be a positive float.Like in support vector machines, smaller values specify strongerregularization. `C=np.inf` results in unpenalized logistic regression.For a visual example on the effect of tuning the `C` parameterwith an L1 penalty, see::ref:`sphx_glr_auto_examples_linear_model_plot_logistic_path.py`.",1.0
,"l1_ratio l1_ratio: float, default=0.0The Elastic-Net mixing parameter, with `0 <= l1_ratio <= 1`. Setting`l1_ratio=1` gives a pure L1-penalty, setting `l1_ratio=0` a pure L2-penalty.Any value between 0 and 1 gives an Elastic-Net penalty of the form`l1_ratio * L1 + (1 - l1_ratio) * L2`... warning:: Certain values of `l1_ratio`, i.e. some penalties, may not work with some solvers. See the parameter `solver` below, to know the compatibility between the penalty and solver... versionchanged:: 1.8 Default value changed from None to 0.0... deprecated:: 1.8 `None` is deprecated and will be removed in version 1.10. Always use `l1_ratio` to specify the penalty type.",0.0
,"dual dual: bool, default=FalseDual (constrained) or primal (regularized, see also:ref:`this equation `) formulation. Dual formulationis only implemented for l2 penalty with liblinear solver. Prefer `dual=False`when n_samples > n_features.",False
,"tol tol: float, default=1e-4Tolerance for stopping criteria.",0.0001
,"fit_intercept fit_intercept: bool, default=TrueSpecifies if a constant (a.k.a. bias or intercept) should beadded to the decision function.",True
,"intercept_scaling intercept_scaling: float, default=1Useful only when the solver `liblinear` is usedand `self.fit_intercept` is set to `True`. In this case, `x` becomes`[x, self.intercept_scaling]`,i.e. a ""synthetic"" feature with constant value equal to`intercept_scaling` is appended to the instance vector.The intercept becomes``intercept_scaling * synthetic_feature_weight``... note:: The synthetic feature weight is subject to L1 or L2 regularization as all other features. To lessen the effect of regularization on synthetic feature weight (and therefore on the intercept) `intercept_scaling` has to be increased.",1
,"class_weight class_weight: dict or 'balanced', default=NoneWeights associated with classes in the form ``{class_label: weight}``.If not given, all classes are supposed to have weight one.The ""balanced"" mode uses the values of y to automatically adjustweights inversely proportional to class frequencies in the input dataas ``n_samples / (n_classes * np.bincount(y))``.Note that these weights will be multiplied with sample_weight (passedthrough the fit method) if sample_weight is specified... versionadded:: 0.17 *class_weight='balanced'*",None
,"random_state random_state: int, RandomState instance, default=NoneUsed when ``solver`` == 'sag', 'saga' or 'liblinear' to shuffle thedata. See :term:`Glossary ` for details.",None
,"solver solver: {'lbfgs', 'liblinear', 'newton-cg', 'newton-cholesky', 'sag', 'saga'}, default='lbfgs'Algorithm to use in the optimization problem. Default is 'lbfgs'.To choose a solver, you might want to consider the following aspects:- 'lbfgs' is a good default solver because it works reasonably well for a wide class of problems.- For :term:`mul

In [172]:
y_test

array([0, 0, 0, 1, 2, 2, 1, 1, 0, 2, 2, 2, 2, 2, 1, 2, 0, 2, 0, 0, 1, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 0, 2, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2, 0, 1, 2, 2,
       2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0,
       1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0])

In [173]:
y_pred = model.predict(x_test)
y_pred

array([0, 0, 0, 1, 2, 2, 1, 0, 0, 2, 2, 2, 0, 2, 1, 2, 0, 2, 0, 0, 1, 0,
       2, 2, 0, 0, 0, 2, 0, 1, 0, 2, 2, 0, 0, 2, 2, 2, 2, 0, 1, 1, 2, 0,
       0, 2, 1, 2, 1, 2, 0, 2, 2, 2, 0, 1, 0, 1, 2, 0, 2, 2, 0, 1, 2, 2,
       2, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 0, 2, 0, 0, 2, 1, 0, 1, 2, 0, 0,
       1, 0, 2, 0, 0, 2, 2, 2, 0, 0, 0, 1, 2, 0, 2, 0])

In [174]:
from sklearn.metrics import accuracy_score,confusion_matrix
print(accuracy_score(y_test,y_pred))
print(confusion_matrix(y_test,y_pred))

0.9711538461538461
[[42  1  0]
 [ 1 15  0]
 [ 1  0 44]]


# now predict by giving some random values to it.

In [189]:
result = model.predict([[45,14,212,65]])
if result[0] == 0:
    print('Penguin belongs to Adelie species')
elif result[0] == 1:
    print('Penguin belongs to Chinstrap Species')
else:
    print("Penguin belongs to Gentoo species")

Penguin belongs to Gentoo species


In [197]:
model.predict([[50,17,200,3.5]])

array([1])